CREATE DATABASE Game_Sales;
USE Game_Sales;

CREATE TABLE Games
(
id INTEGER PRIMARY KEY NOT NULL,
Title VARCHAR(100) NOT NULL,
Release_Date DATE NOT NULL,
Metascore INTEGER NOT NULL
);

CREATE TABLE Category
(
id INTEGER PRIMARY KEY NOT NULL,
Main_Category VARCHAR(50) NOT NULL,
Genre VARCHAR(10) NOT NULL
);

CREATE TABLE Shops
(
id INTEGER NOT NULL, FOREIGN KEY (id) REFERENCES Games(id) ON DELETE CASCADE,
Shop_Name VARCHAR(100) NOT NULL,
Price INTEGER NOT NULL,
On_Sale INTEGER NOT NULL
);
