CREATE DATABASE Game_Sales;
USE Game_Sales;

CREATE TABLE Games
(
id INTEGER PRIMARY KEY NOT NULL,
Title VARCHAR(100) NOT NULL,
Release_Date DATE NOT NULL,
Metascore INTEGER NOT NULL
);

CREATE TABLE Categories
(
id INTEGER PRIMARY KEY NOT NULL,
Genre VARCHAR(10) NOT NULL
);

CREATE TABLE Shops
(
id INTEGER PRIMARY KEY NOT NULL,
Shop_Name VARCHAR(100) NOT NULL
);

CREATE TABLE Prices
(
id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
GameId INTEGER NOT NULL, FOREIGN KEY (GameId) REFERENCES Games(id) ON DELETE CASCADE,
ShopId INTEGER NOT NULL, FOREIGN KEY (ShopId) REFERENCES Shops(id) ON DELETE CASCADE,
Price INTEGER NOT NULL,
On_Sale INTEGER NOT NULL
);

CREATE TABLE Sales
(
id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
GameId INTEGER NOT NULL, FOREIGN KEY (GameId) REFERENCES Games(id) ON DELETE CASCADE,
CategoryId INTEGER NOT NULL, FOREIGN KEY (CategoryId) REFERENCES Categories(id) ON DELETE CASCADE,
ShopId INTEGER NOT NULL, FOREIGN KEY (ShopId) REFERENCES Shops(id) ON DELETE CASCADE
);
